FROM iusdev.azurecr.io/dotnet-runtime:latest AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM iusdev.azurecr.io/{{docker-build-image}}:latest AS build
ARG version=0.0.0
WORKDIR /src
COPY ["NuGet.Config", "src/"]

{{#projects}}    
COPY {{{.}}}/*.csproj {{{.}}}/
{{/projects}}

RUN echo "Setting Version To $version" && \
    find src/ -type f -iname '*.csproj' -exec  sed -i "s/0\.0\.0\-INTERNAL/$version/g" "{}" \; && \
    grep "<VersionPrefix>.*</VersionPrefix>" -R .

WORKDIR src/{{entry_project_directory}}
RUN dotnet restore {{entry_project_name}}.csproj

RUN python /data/post_restore.py --base_path $(pwd) --state_code {{state_code}}

COPY . .
RUN dotnet build "{{entry_project_name}}.csproj" -c Release -o /app --no-restore

FROM build AS publish
RUN dotnet publish "{{entry_project_name}}.csproj" -c Release -o /app --no-build

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "{{entry_project_name}}.dll"]
