FROM iusdev.azurecr.io/dotnet-runtime:latest AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM iusdev.azurecr.io/web-build:latest AS build
ARG version=0.0.0
WORKDIR /src
COPY ["NuGet.Config", "src/"]
{{#projects}}
    COPY {{{.}}}/*.csproj {{{.}}}/
{{/projects}}

RUN echo "Setting Version To $version"
RUN find src/ -type f -iname '*.csproj' -exec  sed -i "s/0\.0\.0\-INTERNAL/$version/g" "{}" \;
RUN grep "<VersionPrefix>.*</VersionPrefix>" -R .

WORKDIR "src/{{entry_project}}"
RUN dotnet restore {{entry_project}}

COPY . .
RUN dotnet build "{{entry_project}}.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "{{entry_project}}.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "{{entry_project}}.dll"]
